packages:
  - 'apps/studio'
  - 'apps/ui-library'
  - 'packages/*'
  - 'e2e/*'

catalog:
  '@types/node': ^22.0.0
  '@supabase/auth-js': 2.71.1-rc.1
  '@supabase/supabase-js': ^2.47.14
  '@supabase/realtime-js': ^2.11.3
  'next': 16.0.7
  'next-auth': '^4.24.13'
  'react': '^18.3.1'
  'react-dom': '^18.3.1'
  '@types/react': '^18.3.1'
  '@types/react-dom': '^18.3.1'
  'valtio': '^1.12.0'
  'vite': '^6.2.7'
