import {
  Activity,
  Cpu,
  Database,
  GaugeCircle,
  HardDrive,
} from 'lucide-react'

import type {
  BillingCycle,
  BranchUsageRow,
  ExportOption,
  ResourceMetricDefinition,
} from './types'

export const BILLING_CYCLES: BillingCycle[] = [
  {
    id: '2025-10',
    label: 'October 2025',
    month: 'October',
    year: 2025,
    start: '2025-10-01T00:00:00Z',
    end: '2025-10-31T23:59:59Z',
    status: 'Current',
    activeProjects: 18,
    totalRuntimeHours: 48_230,
    metrics: {
      vCpuHours: 218_400,
      ramHours: 342_180,
      iopsHours: 128_430,
      dbStorageHours: 88_450,
      storageHours: 162_340,
    },
  },
  {
    id: '2024-09',
    label: 'September 2024',
    month: 'September',
    year: 2024,
    start: '2024-09-01T00:00:00Z',
    end: '2024-09-30T23:59:59Z',
    status: 'Closed',
    activeProjects: 17,
    totalRuntimeHours: 45_120,
    metrics: {
      vCpuHours: 206_750,
      ramHours: 325_110,
      iopsHours: 119_540,
      dbStorageHours: 83_210,
      storageHours: 153_870,
    },
  },
  {
    id: '2024-08',
    label: 'August 2024',
    month: 'August',
    year: 2024,
    start: '2024-08-01T00:00:00Z',
    end: '2024-08-31T23:59:59Z',
    status: 'Closed',
    activeProjects: 16,
    totalRuntimeHours: 43_780,
    metrics: {
      vCpuHours: 198_320,
      ramHours: 311_440,
      iopsHours: 112_760,
      dbStorageHours: 79_240,
      storageHours: 146_980,
    },
  },
  {
    id: '2024-07',
    label: 'July 2024',
    month: 'July',
    year: 2024,
    start: '2024-07-01T00:00:00Z',
    end: '2024-07-31T23:59:59Z',
    status: 'Closed',
    activeProjects: 16,
    totalRuntimeHours: 42_210,
    metrics: {
      vCpuHours: 192_740,
      ramHours: 300_520,
      iopsHours: 109_350,
      dbStorageHours: 76_820,
      storageHours: 140_430,
    },
  },
  {
    id: '2024-11',
    label: 'November 2024',
    month: 'November',
    year: 2024,
    start: '2024-11-01T00:00:00Z',
    end: '2024-11-30T23:59:59Z',
    status: 'Upcoming',
    activeProjects: 19,
    totalRuntimeHours: 0,
    metrics: {
      vCpuHours: 0,
      ramHours: 0,
      iopsHours: 0,
      dbStorageHours: 0,
      storageHours: 0,
    },
  },
]

export const RESOURCE_METRICS: ResourceMetricDefinition[] = [
  {
    key: 'vCpuHours',
    label: 'vCPU Hours',
    summarySuffix: 'compute hours across projects',
    icon: <Cpu size={18} />,
  },
  {
    key: 'ramHours',
    label: 'RAM Hours',
    summarySuffix: 'memory hours delivered on average',
    icon: <GaugeCircle size={18} />,
  },
  {
    key: 'iopsHours',
    label: 'IOPS Hours',
    summarySuffix: 'I/O operations provisioned each month',
    icon: <Activity size={18} />,
  },
  {
    key: 'dbStorageHours',
    label: 'DB Storage Hours',
    summarySuffix: 'database storage hours under management',
    icon: <Database size={18} />,
  },
  {
    key: 'storageHours',
    label: 'Storage Hours',
    summarySuffix: 'object storage hours consumed',
    icon: <HardDrive size={18} />,
  },
]

export const BASE_BRANCH_USAGE: BranchUsageRow[] = [
  {
    id: 'row-1',
    project: 'analytics-api',
    branch: 'main',
    environment: 'production',
    vCpuHours: 4_820,
    ramHours: 6_280,
    iopsHours: 1_830,
    dbStorageHours: 1_240,
    storageHours: 1_520,
    totalRuntime: 8_120,
  },
  {
    id: 'row-2',
    project: 'analytics-api',
    branch: 'preview/dataviz',
    environment: 'test',
    vCpuHours: 1_210,
    ramHours: 1_890,
    iopsHours: 620,
    dbStorageHours: 340,
    storageHours: 580,
    totalRuntime: 2_340,
  },
  {
    id: 'row-3',
    project: 'realtime-engine',
    branch: 'main',
    environment: 'production',
    vCpuHours: 5_120,
    ramHours: 7_010,
    iopsHours: 2_140,
    dbStorageHours: 1_620,
    storageHours: 2_100,
    totalRuntime: 8_950,
  },
  {
    id: 'row-4',
    project: 'realtime-engine',
    branch: 'feature/socket-v2',
    environment: 'development',
    vCpuHours: 980,
    ramHours: 1_410,
    iopsHours: 470,
    dbStorageHours: 220,
    storageHours: 360,
    totalRuntime: 1_620,
  },
  {
    id: 'row-5',
    project: 'realtime-engine',
    branch: 'benchmarking',
    environment: 'test',
    vCpuHours: 1_410,
    ramHours: 2_020,
    iopsHours: 830,
    dbStorageHours: 310,
    storageHours: 540,
    totalRuntime: 2_740,
  },
  {
    id: 'row-6',
    project: 'auth-service',
    branch: 'main',
    environment: 'production',
    vCpuHours: 3_950,
    ramHours: 5_420,
    iopsHours: 1_540,
    dbStorageHours: 980,
    storageHours: 1_280,
    totalRuntime: 6_720,
  },
  {
    id: 'row-7',
    project: 'auth-service',
    branch: 'feature/passkeys',
    environment: 'development',
    vCpuHours: 820,
    ramHours: 1_180,
    iopsHours: 390,
    dbStorageHours: 180,
    storageHours: 260,
    totalRuntime: 1_380,
  },
  {
    id: 'row-8',
    project: 'auth-service',
    branch: 'preview/email-hardening',
    environment: 'test',
    vCpuHours: 960,
    ramHours: 1_420,
    iopsHours: 410,
    dbStorageHours: 250,
    storageHours: 320,
    totalRuntime: 1_620,
  },
  {
    id: 'row-9',
    project: 'storage-edge',
    branch: 'main',
    environment: 'production',
    vCpuHours: 4_360,
    ramHours: 5_820,
    iopsHours: 1_760,
    dbStorageHours: 1_420,
    storageHours: 1_980,
    totalRuntime: 7_580,
  },
  {
    id: 'row-10',
    project: 'storage-edge',
    branch: 'group-coldline',
    environment: 'development',
    vCpuHours: 1_140,
    ramHours: 1_710,
    iopsHours: 520,
    dbStorageHours: 260,
    storageHours: 410,
    totalRuntime: 2_010,
  },
  {
    id: 'row-11',
    project: 'storage-edge',
    branch: 'preview/object-lifecycle',
    environment: 'test',
    vCpuHours: 1_320,
    ramHours: 1_930,
    iopsHours: 610,
    dbStorageHours: 300,
    storageHours: 480,
    totalRuntime: 2_290,
  },
  {
    id: 'row-12',
    project: 'ai-assistant',
    branch: 'main',
    environment: 'production',
    vCpuHours: 3_620,
    ramHours: 4_950,
    iopsHours: 1_390,
    dbStorageHours: 910,
    storageHours: 1_280,
    totalRuntime: 6_040,
  },
  {
    id: 'row-13',
    project: 'ai-assistant',
    branch: 'experiments/vector-search',
    environment: 'development',
    vCpuHours: 1_520,
    ramHours: 2_110,
    iopsHours: 690,
    dbStorageHours: 430,
    storageHours: 720,
    totalRuntime: 2_860,
  },
  {
    id: 'row-14',
    project: 'analytics-workbench',
    branch: 'main',
    environment: 'production',
    vCpuHours: 3_380,
    ramHours: 4_780,
    iopsHours: 1_210,
    dbStorageHours: 830,
    storageHours: 1_150,
    totalRuntime: 5_620,
  },
  {
    id: 'row-15',
    project: 'analytics-workbench',
    branch: 'feature/chart-builder',
    environment: 'development',
    vCpuHours: 780,
    ramHours: 1_120,
    iopsHours: 320,
    dbStorageHours: 190,
    storageHours: 260,
    totalRuntime: 1_210,
  },
  {
    id: 'row-16',
    project: 'billing-engine',
    branch: 'main',
    environment: 'production',
    vCpuHours: 2_970,
    ramHours: 4_310,
    iopsHours: 1_030,
    dbStorageHours: 710,
    storageHours: 1_040,
    totalRuntime: 4_980,
  },
  {
    id: 'row-17',
    project: 'billing-engine',
    branch: 'feature/forecasting',
    environment: 'development',
    vCpuHours: 980,
    ramHours: 1_620,
    iopsHours: 480,
    dbStorageHours: 250,
    storageHours: 360,
    totalRuntime: 1_820,
  },
  {
    id: 'row-18',
    project: 'developer-portal',
    branch: 'main',
    environment: 'production',
    vCpuHours: 2_140,
    ramHours: 3_560,
    iopsHours: 940,
    dbStorageHours: 530,
    storageHours: 760,
    totalRuntime: 3_920,
  },
  {
    id: 'row-19',
    project: 'developer-portal',
    branch: 'preview/beta-docs',
    environment: 'test',
    vCpuHours: 680,
    ramHours: 980,
    iopsHours: 310,
    dbStorageHours: 170,
    storageHours: 240,
    totalRuntime: 1_080,
  },
  {
    id: 'row-20',
    project: 'events-pipeline',
    branch: 'main',
    environment: 'production',
    vCpuHours: 3_280,
    ramHours: 4_520,
    iopsHours: 1_190,
    dbStorageHours: 760,
    storageHours: 1_090,
    totalRuntime: 5_480,
  },
]

export const EXPORT_OPTIONS: ExportOption[] = [
  {
    value: 'excel',
    label: 'Excel (.xlsx)',
    description: 'Best for pivot tables or ad-hoc analysis.',
  },
  {
    value: 'pdf',
    label: 'PDF (.pdf)',
    description: 'Snapshot report for sharing with stakeholders.',
  },
]
